package org.onvif.ver10.recording.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", name = "RecordingPort")
@XmlSeeAlso({org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class, org.w3._2004._08.xop.include.ObjectFactory.class, org.onvif.ver10.schema.ObjectFactory.class, org.oasis_open.docs.wsn.b_2.ObjectFactory.class, org.oasis_open.docs.wsn.t_1.ObjectFactory.class, ObjectFactory.class, org.w3._2003._05.soap_envelope.ObjectFactory.class, org.w3._2005._05.xmlmime.ObjectFactory.class})
public interface RecordingPort {

    /**
     * GetRecordings shall return a description of all the recordings in the
     *         device. This description
     *         shall include a list of all the tracks for each recording.
     *       
     */
    @WebMethod(operationName = "GetRecordings", action = "http://www.onvif.org/ver10/recording/wsdl/GetRecordings")
    @RequestWrapper(localName = "GetRecordings", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordings")
    @ResponseWrapper(localName = "GetRecordingsResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingsResponse")
    @WebResult(name = "RecordingItem", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public java.util.List<org.onvif.ver10.schema.GetRecordingsResponseItem> getRecordings()
;

    /**
     * DeleteTrack shall remove a track from a recording. All the data in the
     *         track shall be deleted.
     *         
     *         This method is optional. It shall be available if the Recording/DynamicTracks capability is
     *         TRUE.
     *       
     */
    @WebMethod(operationName = "DeleteTrack", action = "http://www.onvif.org/ver10/recording/wsdl/DeleteTrack")
    @RequestWrapper(localName = "DeleteTrack", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.DeleteTrack")
    @ResponseWrapper(localName = "DeleteTrackResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.DeleteTrackResponse")
    public void deleteTrack(

        @WebParam(name = "RecordingToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String recordingToken,
        @WebParam(name = "TrackToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String trackToken
    );

    /**
     * DeleteRecording shall delete a recording object. Whenever a recording is
     *         deleted, the device
     *         shall delete all the tracks that are part of the recording, and it shall delete all the
     *         Recording
     *         Jobs that record into the recording. For each deleted recording job, the device shall also
     *         delete all the receiver objects associated with the recording job that are automatically
     *         created
     *         using the AutoCreateReceiver field of the recording job configuration structure and are not
     *         used in any other recording job.
     *         
     *         This method is optional. It shall be available if the Recording/DynamicRecordings capability
     *         is TRUE.
     *       
     */
    @WebMethod(operationName = "DeleteRecording", action = "http://www.onvif.org/ver10/recording/wsdl/DeleteRecording")
    @RequestWrapper(localName = "DeleteRecording", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.DeleteRecording")
    @ResponseWrapper(localName = "DeleteRecordingResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.DeleteRecordingResponse")
    public void deleteRecording(

        @WebParam(name = "RecordingToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String recordingToken
    );

    /**
     * This method shall create a new track within a recording.
     *         
     *         This method is optional. It shall be available if the Recording/DynamicTracks capability is
     *         TRUE.
     *         
     *         A TrackToken in itself does not uniquely identify a specific track. Tracks within different
     *         recordings may have the same TrackToken.
     *       
     */
    @WebMethod(operationName = "CreateTrack", action = "http://www.onvif.org/ver10/recording/wsdl/CreateTrack")
    @RequestWrapper(localName = "CreateTrack", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.CreateTrack")
    @ResponseWrapper(localName = "CreateTrackResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.CreateTrackResponse")
    @WebResult(name = "TrackToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public java.lang.String createTrack(

        @WebParam(name = "RecordingToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String recordingToken,
        @WebParam(name = "TrackConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        org.onvif.ver10.schema.TrackConfiguration trackConfiguration
    );

    /**
     * GetRecordingJobs shall return a list of all the recording jobs in the
     *         device.
     *       
     */
    @WebMethod(operationName = "GetRecordingJobs", action = "http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobs")
    @RequestWrapper(localName = "GetRecordingJobs", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingJobs")
    @ResponseWrapper(localName = "GetRecordingJobsResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingJobsResponse")
    @WebResult(name = "JobItem", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public java.util.List<org.onvif.ver10.schema.GetRecordingJobsResponseItem> getRecordingJobs()
;

    /**
     * SetRecordingJobConfiguration shall change the configuration for a
     *         recording job.
     *         
     *         SetRecordingJobConfiguration shall implicitly delete any receiver objects that were created
     *         automatically if they are no longer used as a result of changing the recording job
     *         configuration.
     *       
     */
    @WebMethod(operationName = "SetRecordingJobConfiguration", action = "http://www.onvif.org/ver10/recording/wsdl/SetRecordingJobConfiguration")
    @RequestWrapper(localName = "SetRecordingJobConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.SetRecordingJobConfiguration")
    @ResponseWrapper(localName = "SetRecordingJobConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.SetRecordingJobConfigurationResponse")
    public void setRecordingJobConfiguration(

        @WebParam(name = "JobToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String jobToken,
        @WebParam(mode = WebParam.Mode.INOUT, name = "JobConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        javax.xml.ws.Holder<org.onvif.ver10.schema.RecordingJobConfiguration> jobConfiguration
    );

    /**
     * SetRecordingConfiguration shall change the configuration of a recording.
     *       
     */
    @WebMethod(operationName = "SetRecordingConfiguration", action = "http://www.onvif.org/ver10/recording/wsdl/SetRecordingConfiguration")
    @RequestWrapper(localName = "SetRecordingConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.SetRecordingConfiguration")
    @ResponseWrapper(localName = "SetRecordingConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.SetRecordingConfigurationResponse")
    public void setRecordingConfiguration(

        @WebParam(name = "RecordingToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String recordingToken,
        @WebParam(name = "RecordingConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        org.onvif.ver10.schema.RecordingConfiguration recordingConfiguration
    );

    /**
     * GetRecordingConfiguration shall retrieve the recording configuration for a
     *         recording.
     *       
     */
    @WebMethod(operationName = "GetRecordingConfiguration", action = "http://www.onvif.org/ver10/recording/wsdl/GetRecordingConfiguration")
    @RequestWrapper(localName = "GetRecordingConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingConfiguration")
    @ResponseWrapper(localName = "GetRecordingConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingConfigurationResponse")
    @WebResult(name = "RecordingConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public org.onvif.ver10.schema.RecordingConfiguration getRecordingConfiguration(

        @WebParam(name = "RecordingToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String recordingToken
    );

    /**
     * Retrieves the status of selected ExportRecordedData operation.
     *       
     */
    @WebMethod(operationName = "GetExportRecordedDataState", action = "http://www.onvif.org/ver10/recording/wsdl/GetExportRecordedDataState")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "GetExportRecordedDataStateResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", partName = "parameters")
    public GetExportRecordedDataStateResponse getExportRecordedDataState(

        @WebParam(partName = "parameters", name = "GetExportRecordedDataState", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        GetExportRecordedDataState parameters
    );

    /**
     * SetRecordingJobMode shall change the mode of the recording job. Using this
     *         method shall be
     *         equivalent to retrieving the recording job configuration, and writing it back with a
     *         different
     *         mode.
     *       
     */
    @WebMethod(operationName = "SetRecordingJobMode", action = "http://www.onvif.org/ver10/recording/wsdl/SetRecordingJobMode")
    @RequestWrapper(localName = "SetRecordingJobMode", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.SetRecordingJobMode")
    @ResponseWrapper(localName = "SetRecordingJobModeResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.SetRecordingJobModeResponse")
    public void setRecordingJobMode(

        @WebParam(name = "JobToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String jobToken,
        @WebParam(name = "Mode", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String mode
    );

    /**
     * GetTrackConfiguration shall retrieve the configuration for a specific
     *         track.
     *       
     */
    @WebMethod(operationName = "GetTrackConfiguration", action = "http://www.onvif.org/ver10/recording/wsdl/GetTrackConfiguration")
    @RequestWrapper(localName = "GetTrackConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetTrackConfiguration")
    @ResponseWrapper(localName = "GetTrackConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetTrackConfigurationResponse")
    @WebResult(name = "TrackConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public org.onvif.ver10.schema.TrackConfiguration getTrackConfiguration(

        @WebParam(name = "RecordingToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String recordingToken,
        @WebParam(name = "TrackToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String trackToken
    );

    /**
     * Exports the selected recordings (from existing recorded data) to the given storage target
     * based on the requested file format.
     *       
     */
    @WebMethod(operationName = "ExportRecordedData", action = "http://www.onvif.org/ver10/recording/wsdl/ExportRecordedData")
    @RequestWrapper(localName = "ExportRecordedData", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.ExportRecordedData")
    @ResponseWrapper(localName = "ExportRecordedDataResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.ExportRecordedDataResponse")
    public void exportRecordedData(

        @WebParam(name = "SearchScope", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        org.onvif.ver10.schema.SearchScope searchScope,
        @WebParam(name = "FileFormat", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String fileFormat,
        @WebParam(name = "StorageDestination", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        org.onvif.ver10.schema.StorageReferencePath storageDestination,
        @WebParam(mode = WebParam.Mode.OUT, name = "OperationToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        javax.xml.ws.Holder<java.lang.String> operationToken,
        @WebParam(mode = WebParam.Mode.OUT, name = "FileNames", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        javax.xml.ws.Holder<java.util.List<java.lang.String>> fileNames,
        @WebParam(mode = WebParam.Mode.OUT, name = "Extension", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        javax.xml.ws.Holder<org.onvif.ver10.recording.wsdl.ExportRecordedDataResponse.Extension> extension
    );

    /**
     * CreateRecording shall create a new recording. The new recording shall be
     *         created with a track
     *         for each supported TrackType see Recording Control Spec.
     *         
     *         This method is optional. It shall be available if the Recording/DynamicRecordings capability
     *         is TRUE.
     *         
     *         When successfully completed, CreateRecording shall have created three tracks with the
     *         following configurations:
     *         
     *         All TrackConfigurations shall have the MaximumRetentionTime set to 0 (unlimited), and the
     *         Description set to the empty string.
     *       
     */
    @WebMethod(operationName = "CreateRecording", action = "http://www.onvif.org/ver10/recording/wsdl/CreateRecording")
    @RequestWrapper(localName = "CreateRecording", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.CreateRecording")
    @ResponseWrapper(localName = "CreateRecordingResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.CreateRecordingResponse")
    @WebResult(name = "RecordingToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public java.lang.String createRecording(

        @WebParam(name = "RecordingConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        org.onvif.ver10.schema.RecordingConfiguration recordingConfiguration
    );

    /**
     * SetTrackConfiguration shall change the configuration of a track.
     *       
     */
    @WebMethod(operationName = "SetTrackConfiguration", action = "http://www.onvif.org/ver10/recording/wsdl/SetTrackConfiguration")
    @RequestWrapper(localName = "SetTrackConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.SetTrackConfiguration")
    @ResponseWrapper(localName = "SetTrackConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.SetTrackConfigurationResponse")
    public void setTrackConfiguration(

        @WebParam(name = "RecordingToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String recordingToken,
        @WebParam(name = "TrackToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String trackToken,
        @WebParam(name = "TrackConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        org.onvif.ver10.schema.TrackConfiguration trackConfiguration
    );

    /**
     * CreateRecordingJob shall create a new recording job.
     *         
     *         The JobConfiguration returned from CreateRecordingJob shall be identical to the
     *         JobConfiguration passed into CreateRecordingJob, except for the ReceiverToken and the
     *         AutoCreateReceiver. In the returned structure, the ReceiverToken shall be present and valid
     *         and the AutoCreateReceiver field shall be omitted.
     *       
     */
    @WebMethod(operationName = "CreateRecordingJob", action = "http://www.onvif.org/ver10/recording/wsdl/CreateRecordingJob")
    @RequestWrapper(localName = "CreateRecordingJob", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.CreateRecordingJob")
    @ResponseWrapper(localName = "CreateRecordingJobResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.CreateRecordingJobResponse")
    public void createRecordingJob(

        @WebParam(mode = WebParam.Mode.INOUT, name = "JobConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        javax.xml.ws.Holder<org.onvif.ver10.schema.RecordingJobConfiguration> jobConfiguration,
        @WebParam(mode = WebParam.Mode.OUT, name = "JobToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        javax.xml.ws.Holder<java.lang.String> jobToken
    );

    /**
     * GetRecordingJobConfiguration shall return the current configuration for a
     *         recording job.
     *       
     */
    @WebMethod(operationName = "GetRecordingJobConfiguration", action = "http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobConfiguration")
    @RequestWrapper(localName = "GetRecordingJobConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingJobConfiguration")
    @ResponseWrapper(localName = "GetRecordingJobConfigurationResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingJobConfigurationResponse")
    @WebResult(name = "JobConfiguration", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public org.onvif.ver10.schema.RecordingJobConfiguration getRecordingJobConfiguration(

        @WebParam(name = "JobToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String jobToken
    );

    /**
     * Stops the selected ExportRecordedData operation.
     *       
     */
    @WebMethod(operationName = "StopExportRecordedData", action = "http://www.onvif.org/ver10/recording/wsdl/StopExportRecordedData")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "StopExportRecordedDataResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", partName = "parameters")
    public StopExportRecordedDataResponse stopExportRecordedData(

        @WebParam(partName = "parameters", name = "StopExportRecordedData", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        StopExportRecordedData parameters
    );

    /**
     * GetRecordingOptions returns information for a recording identified by the
     *         RecordingToken. The information includes the number of additonal tracks as well as recording
     *         jobs that can be configured.
     *       
     */
    @WebMethod(operationName = "GetRecordingOptions", action = "http://www.onvif.org/ver10/recording/wsdl/GetRecordingOptions")
    @RequestWrapper(localName = "GetRecordingOptions", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingOptions")
    @ResponseWrapper(localName = "GetRecordingOptionsResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingOptionsResponse")
    @WebResult(name = "Options", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public org.onvif.ver10.recording.wsdl.RecordingOptions getRecordingOptions(

        @WebParam(name = "RecordingToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String recordingToken
    );

    /**
     * DeleteRecordingJob removes a recording job. It shall also implicitly
     *         delete all the receiver
     *         objects associated with the recording job that are automatically created using the
     *         AutoCreateReceiver field of the recording job configuration structure and are not used in
     *         any
     *         other recording job.
     *       
     */
    @WebMethod(operationName = "DeleteRecordingJob", action = "http://www.onvif.org/ver10/recording/wsdl/DeleteRecordingJob")
    @RequestWrapper(localName = "DeleteRecordingJob", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.DeleteRecordingJob")
    @ResponseWrapper(localName = "DeleteRecordingJobResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.DeleteRecordingJobResponse")
    public void deleteRecordingJob(

        @WebParam(name = "JobToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String jobToken
    );

    /**
     * Returns the capabilities of the recording service. The result is returned
     *         in a typed answer.
     *       
     */
    @WebMethod(operationName = "GetServiceCapabilities", action = "http://www.onvif.org/ver10/recording/wsdl/GetServiceCapabilities")
    @RequestWrapper(localName = "GetServiceCapabilities", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetServiceCapabilities")
    @ResponseWrapper(localName = "GetServiceCapabilitiesResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetServiceCapabilitiesResponse")
    @WebResult(name = "Capabilities", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public org.onvif.ver10.recording.wsdl.Capabilities getServiceCapabilities()
;

    /**
     * GetRecordingJobState returns the state of a recording job. It includes an
     *         aggregated state,
     *         and state for each track of the recording job.
     *       
     */
    @WebMethod(operationName = "GetRecordingJobState", action = "http://www.onvif.org/ver10/recording/wsdl/GetRecordingJobState")
    @RequestWrapper(localName = "GetRecordingJobState", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingJobState")
    @ResponseWrapper(localName = "GetRecordingJobStateResponse", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl", className = "org.onvif.ver10.recording.wsdl.GetRecordingJobStateResponse")
    @WebResult(name = "State", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
    public org.onvif.ver10.schema.RecordingJobStateInformation getRecordingJobState(

        @WebParam(name = "JobToken", targetNamespace = "http://www.onvif.org/ver10/recording/wsdl")
        java.lang.String jobToken
    );
}
