#!/bin/bash

export path=$1
export dir
export basename
dir=$(dirname "$path")

basename=$(basename "${path%.*}")

# Convert the file produced by motion to an hls file group :q

ffmpeg -i "$1" -c copy -level 3.0 -start_number 0 -hls_time 10 -hls_list_size 0 -hls_segment_type fmp4 -hls_fmp4_init_filename ${basename}_.mp4 -f hls "$dir"/"${basename}"_.m3u8

# Processing done so remove the recording file generated by motion
rm "$1"
# Remove oldest recording files
find "$dir" -mtime +21 -delete

