package org.onvif.ver10.display.wsdl;

import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "DisplayService",
                  wsdlLocation = "null",
                  targetNamespace = "http://www.onvif.org/ver10/display/wsdl")
public class DisplayService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://www.onvif.org/ver10/display/wsdl", "DisplayService");
    public static final QName DisplayPort = new QName("http://www.onvif.org/ver10/display/wsdl", "DisplayPort");
    static {
        WSDL_LOCATION = null;
    }

    public DisplayService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DisplayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DisplayService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DisplayService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DisplayService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DisplayService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DisplayPort
     */
    @WebEndpoint(name = "DisplayPort")
    public DisplayPort getDisplayPort() {
        return super.getPort(DisplayPort, DisplayPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DisplayPort
     */
    @WebEndpoint(name = "DisplayPort")
    public DisplayPort getDisplayPort(WebServiceFeature... features) {
        return super.getPort(DisplayPort, DisplayPort.class, features);
    }

}
