
package org.oasis_open.docs.wsn.bw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 */

@WebFault(name = "InvalidMessageContentExpressionFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class InvalidMessageContentExpressionFault extends Exception {

    private org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault;

    public InvalidMessageContentExpressionFault() {
        super();
    }

    public InvalidMessageContentExpressionFault(String message) {
        super(message);
    }

    public InvalidMessageContentExpressionFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidMessageContentExpressionFault(String message, org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault) {
        super(message);
        this.invalidMessageContentExpressionFault = invalidMessageContentExpressionFault;
    }

    public InvalidMessageContentExpressionFault(String message, org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidMessageContentExpressionFault = invalidMessageContentExpressionFault;
    }

    public org.oasis_open.docs.wsn.b_2.InvalidMessageContentExpressionFaultType getFaultInfo() {
        return this.invalidMessageContentExpressionFault;
    }
}
