package org.onvif.ver10.network.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://www.onvif.org/ver10/network/wsdl", name = "DiscoveryLookupPort")
@XmlSeeAlso({org.xmlsoap.schemas.ws._2005._04.discovery.ObjectFactory.class, ObjectFactory.class, org.xmlsoap.schemas.ws._2004._08.addressing.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DiscoveryLookupPort {

    @WebMethod(operationName = "Probe", action = "http://www.onvif.org/ver10/network/wsdl/Probe")
    @WebResult(name = "ProbeResponse", targetNamespace = "http://www.onvif.org/ver10/network/wsdl", partName = "parameters")
    public org.xmlsoap.schemas.ws._2005._04.discovery.ProbeMatchesType probe(

        @WebParam(partName = "parameters", name = "Probe", targetNamespace = "http://www.onvif.org/ver10/network/wsdl")
        org.xmlsoap.schemas.ws._2005._04.discovery.ProbeType parameters
    );
}
