package org.onvif.ver10.replay.wsdl;

import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.5
 * Generated source version: 4.0.5
 *
 */
@WebServiceClient(name = "ReplayService",
                  wsdlLocation = "null",
                  targetNamespace = "http://www.onvif.org/ver10/replay/wsdl")
public class ReplayService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://www.onvif.org/ver10/replay/wsdl", "ReplayService");
    public static final QName ReplayPort = new QName("http://www.onvif.org/ver10/replay/wsdl", "ReplayPort");
    static {
        WSDL_LOCATION = null;
    }

    public ReplayService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ReplayService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReplayService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ReplayService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ReplayService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ReplayService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ReplayPort
     */
    @WebEndpoint(name = "ReplayPort")
    public ReplayPort getReplayPort() {
        return super.getPort(ReplayPort, ReplayPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReplayPort
     */
    @WebEndpoint(name = "ReplayPort")
    public ReplayPort getReplayPort(WebServiceFeature... features) {
        return super.getPort(ReplayPort, ReplayPort.class, features);
    }

}
