
package org.oasis_open.docs.wsrf.rw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 */

public class ResourceUnknownFault extends Exception {
}
