#!/bin/bash

cp /tmp/motion.conf /etc/motion
mv /tmp/nginx.conf /etc/nginx
mv /tmp/chrony.conf /etc/chrony
mv /tmp/server.xml /var/lib/tomcat10/conf
#### mv /tmp/tomcat10 /etc/default/  # Updated tomcat10 default file to enable use of Java 17
mv /tmp/tomcat-users.xml /var/lib/tomcat10/conf
mv /tmp/server-0.0.1.war /var/lib/tomcat10/webapps/ROOT.war
mv /tmp/cua.war /var/lib/tomcat10/webapps/cua.war
# Get the drawdown calculator from the 2.1.0 release area
wget -O /var/lib/tomcat10/webapps/dc.war https://github.com/richard-austin/drawdown-calculator/releases/download/2.1.0/dc.war

rm -rf /var/lib/tomcat10/webapps/ROOT
rm -rf /var/lib/tomcat10/webapps/cua

rm -r /tmp/motion.conf
deb-systemd-invoke stop tomcat10.service  # Stop tomcat before making changes
deb-systemd-invoke stop motion  # And motion
sleep 2

groupadd security-cam
usermod -a -G video tomcat
usermod -a -G security-cam tomcat
usermod -a -G security-cam www-data

chown -R tomcat:security-cam /etc/security-cam
chown -R tomcat:security-cam /var/security-cam

chown tomcat:security-cam /var/log/security-cam/security-cam.log*  # To prevent access denied errors on first starting tomcat
chown -R tomcat:tomcat /var/lib/tomcat10

# Create the client keystore for connection to the Cloud server via ActiveMQ
MQ_CREDS_FILE=/var/security-cam/cloud-creds.json
KEYSTORE_FILE=/etc/security-cam/client.ks
if ! test -f "$MQ_CREDS_FILE"; then
  KS_PASSWORD_CLIENT=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 40)
  keytool -genkey -alias client -dname "cn=NVR USER, ou=Private, o=Private, c=Unknown st=Unknown" -keypass "$KS_PASSWORD_CLIENT" -storepass "$KS_PASSWORD_CLIENT" -keyalg RSA -keystore $KEYSTORE_FILE
  cat > $MQ_CREDS_FILE << EOF
{
   "mqClientKSPath": "${KEYSTORE_FILE}",
   "mqClientKSPW": "${KS_PASSWORD_CLIENT}",
   "mqUser": "",
   "mqPw": "",
   "mqHost": "192.168.1.82"
}
EOF
  chmod 440 $MQ_CREDS_FILE
  chown tomcat:root $MQ_CREDS_FILE
  chown tomcat:tomcat $KEYSTORE_FILE
  chmod 400 $KEYSTORE_FILE
fi

chmod 640 /var/lib/tomcat10/conf/tomcat-users.xml
chown root:tomcat /var/lib/tomcat10/conf/tomcat-users.xml
chmod 640 /var/lib/tomcat10/conf/server.xml
chown root:tomcat /var/lib/tomcat10/conf/server.xml
chown root:root /etc/security-cam/wifi-setup-service/*.py
chown tomcat:tomcat -R /etc/fmp4-ws-media-server

# Give directories only permission 775
find /etc/security-cam -type d -print0 | xargs -0 chmod 775
# Give files permission 664
find /etc/security-cam -type f -print0 | xargs -0 chmod 664

chgrp -R security-cam /etc/security-cam/
chown -R tomcat:security-cam /var/log/motion
chown -R tomcat:security-cam /var/log/security-cam
chown -R tomcat:security-cam /var/log/camera-recordings-service
chown -R tomcat:security-cam /var/log/fmp4-ws-media-service
chown -R tomcat:tomcat /var/log/tomcat10
# Make the following scripts executable
chmod +x /etc/security-cam/install-cert.sh
chmod +x /etc/security-cam/processmotionrecordings.sh || true
chmod +x /etc/security-cam/productKeyGen.sh || true

pushd /etc/security-cam/camera-recordings-service || true
sudo -u tomcat python3 -m venv .  # Create Python3 virtual environment
sudo -u tomcat bin/pip install -r requirements.txt --use-pep517

pushd /etc/security-cam/wifi-setup-service || true
python3 -m venv .  # Create Python3 virtual environment
bin/pip install -r requirements.txt
popd || true
popd || true


# Change the motion service user to tomcat
sed -i 's/User=motion/User=tomcat/' /lib/systemd/system/motion.service

#
# AddToTomcatUnitFileIfNotPresent: Add ReadWriteFilePaths to the tomcat unit file to enable access to /etc/security-cam
#                                  and /var/log/security-cam.
#
AddToTomcatUnitFileIfNotPresent() {
  lineToWrite=$1
  lineToWriteUnder=$2
  unitFile=$3
  # Enter lineToWrite after lineToWriteUnder if not already present
  if ! grep "$lineToWrite" "$unitFile"; then
    # Add the line after lineToWriteUnder escaping all '/' as the regex is within / delimiters.
    result=$(awk '/'"${lineToWriteUnder//\//\\/}"'/ { print; print '\""${lineToWrite}"\"'; next }1' "$unitFile")
    echo "$result" >"$unitFile"
  fi
}

# Give tomcat permission to write to some additional directories
lineToWrite="ReadWritePaths=/var/log/security-cam/"
lineToWrite2="ReadWritePaths=/etc/security-cam/"
lineToWrite3="ReadWritePaths=/var/security-cam/"
lineToWriteUnder="ReadWritePaths=/var/log/tomcat10/"
unitFile="/usr/lib/systemd/system/tomcat10.service"

AddToTomcatUnitFileIfNotPresent $lineToWrite $lineToWriteUnder $unitFile
AddToTomcatUnitFileIfNotPresent $lineToWrite2 $lineToWriteUnder $unitFile
AddToTomcatUnitFileIfNotPresent $lineToWrite3 $lineToWriteUnder $unitFile

systemctl daemon-reload  # Register the motion service file change

# Start the services
deb-systemd-invoke enable motion.service
deb-systemd-invoke enable nginx.service
deb-systemd-invoke enable fmp4-ws-media-server

deb-systemd-invoke enable wifimanagement.service
deb-systemd-invoke start wifimanagement.service
deb-systemd-invoke enable camera-recordings.service

CERT_FILE=/etc/nginx/security-cam.crt
if [ ! -f "$CERT_FILE" ]; then
  # Create the default security certificates for nginx SSL (may be changed with the install-cert.sh script
  openssl req -x509 -newkey rsa:4096 -keyout security-cam.key -out security-cam.crt -nodes -days 2000 -subj "/C=UA/ST=anywhere/L=anywhere/O=MyNVR/OU=IT Department/CN=example.com"
  mv security-cam.key security-cam.crt /etc/nginx
fi

deb-systemd-invoke start nginx.service

# Let chrony use the updated conf file
deb-systemd-invoke stop chrony
deb-systemd-invoke start chrony

deb-systemd-invoke enable tomcat10.service
deb-systemd-invoke start tomcat10.service


# Generate the product key if it does not already exist
cd /etc/security-cam/ || exit
./productKeyGen.sh

# Generate the key pair for camera credentials encryption/decryption if they don't already exist
PRIVATE_KEY=/etc/security-cam/id_rsa
if [ ! -f "$PRIVATE_KEY" ]; then
  cd /etc/security-cam/ || exit
  # Generate private key
  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -pkeyopt rsa_keygen_pubexp:65537 | openssl pkcs8 -topk8 -nocrypt -outform der > /etc/security-cam/id_rsa
  # Generate the public key from the private key
  openssl pkey -pubout -inform der -outform der -in /etc/security-cam/id_rsa -out /etc/security-cam/id_rsa.pub
  chown tomcat:security-cam /etc/security-cam/id_rsa
  chown tomcat:security-cam /etc/security-cam/id_rsa.pub
fi

