#!/bin/bash

deb-systemd-invoke disable nginx.service
deb-systemd-invoke stop nginx.service
deb-systemd-invoke disable tomcat9.service
deb-systemd-invoke stop tomcat9.service
deb-systemd-invoke disable motion.service
deb-systemd-invoke stop motion.service
deb-systemd-invoke disable fmp4-ws-media-server.service
deb-systemd-invoke stop fmp4-ws-media-server.service

deb-systemd-invoke stop wifimanagement.service
deb-systemd-invoke disable wifimanagement.service
deb-systemd-invoke stop camera-recordings.service
deb-systemd-invoke disable camera-recordings.service
