# @no-redirect
POST http://localhost:8080/login/authenticate HTTP/1.1
# Host: localhost
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Content-Type: application/x-www-form-urlencoded
# Origin: https://149.22.128.178
Connection: keep-alive
x-auth-token: 7yk=zJu+@77x@MTJG2HD*YLJgvBthkW!
# Referer: http://localhost/login/auth
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Priority: u=0, i

username=cloud&password=DrN3yuFAtSsK2w7AtTf66FFRVveBwtjU

<> 2024-10-15T185231.200.html
<> 2024-10-15T185141.200.html
<> 2024-10-15T184954.200.html
<> 2024-10-15T184848.200.html

###
POST http://localhost:8080/cam/getCameras
Cookie: Idea-5846b23=e7e28179-dafb-4e30-934d-7945085e96e4; JSESSIONID=C78493F4365FB8C2C7164D06DFE5BA22

<> 2024-10-20T124322.200.json
<> 2024-10-20T124312.200.json
<> 2024-10-20T124107.200.html
<> 2024-10-20T124058.200.json
<> 2024-10-19T212426.200.json
<> 2024-10-19T145102.409.txt
<> 2024-10-19T144430.200.json
<> 2024-10-19T144227.200.html

###
POST https://149.22.128.178/cam/getPublicKey
Cookie: Idea-5846b23=e7e28179-dafb-4e30-934d-7945085e96e4; JSESSIONID=C78493F4365FB8C2C7164D06DFE5BA22

<> 2024-10-20T124001.200.html
<> 2024-10-19T224752.200.html
<> 2024-10-19T224639.200.html
<> 2024-10-19T213347.200.html
<> 2024-10-19T212918.200.html

###

POST localhost:8080/cam/getPublicKey
Cookie: Idea-5846b23=e7e28179-dafb-4e30-934d-7945085e96e4; JSESSIONID=C78493F4365FB8C2C7164D06DFE5BA2p

<> 2024-10-20T124333.200.octet-stream
<> 2024-10-20T124038.200.octet-stream
<> 2024-10-20T123157.200.octet-stream
<> 2024-10-19T225054.200.octet-stream
<> 2024-10-19T225008.200.html
<> 2024-10-19T224754.200.octet-stream

###

POST http://192.168.1.136:8080/utils/getTemperature
Cookie: JSESSIONID=6FB9F149CB2DFEE9E5B2AF96C78D112D

###
POST http://localhost:8080/utils/startAudioOut
Content-Type: application/json

{
  "cam": {
    "address": "192.168.1.43",
    "backchannelAudioSupported": true,
    "cameraParamSpecs": {
      "camType": 0,
      "params": "",
      "uri": "",
      "name": "Not Listed"
    },
    "cred": "eCCvpyP2xlQBAf1IbklAzeq1BtflUGh6QRclJk5AsOllCBu9J++YjR7Cq8jgkKhApHlwPcQbexnBjiMpRAHC4CIXgZdvCHpgIpeUF7FozU1MTY8v6Jc0nl5XZ8Ed5AgGgxEAhYKL4pPLO1FQO/Q3ZwBazqBJ6rN9IDGZYq6FPxOtxFNjLHPC8novnWMMM+SlLGgktj0i62UyQFtxX0tOhcx75hG7sXqJNlkYXEwv32XaQkj8F1JW6KuUh/LG0RolpQzqASi+15qFB5seGKWNHkXktFD/nDeI6WiR9mZV8MvC+ScvCdMqKn0ARVH0aCZu0h/s0mgP7F/fxuFQVMwyvQ==",
    "ftp": "stream9",
    "name": "Doorbell",
    "onvifHost": "192.168.1.43:8000",
    "ptzControls": false,
    "retriggerWindow": 30,
    "rtspTransport": "tcp",
    "snapshotUri": "http://192.168.1.43/cgi-bin/api.cgi?cmd=onvifSnapPic&channel=0",
    "streams": {},
    "useRtspAuth": true
  },
  "netcam_uri": "rtsp://192.168.1.43:554/Preview_01_main"
}
###
POST http://localhost:8080/motion/getMotionEvents
Content-Type: application/json

{
  "cam": {
    "address": "192.168.1.30",
    "backchannelAudioSupported": false,
    "cameraParamSpecs": {
      "camType": 2,
      "params": "cmd=getvideoattr&cmd=getlampattrex&cmd=getimageattr&cmd=getinfrared&cmd=getserverinfo&cmd=getoverlayattr&-region=0&cmd=getserverinfo&cmd=getoverlayattr&-region=1",
      "uri": "web/cgi-bin/hi3510/param.cgi",
      "name": "ZTech MCW5B10X"
    },
    "cred": "JFM3r9UZRmLGPN4ts+xjQSco3tjM07DD5ITS0kviMzVttgqUBLc0b+kpLn88+mTPj6esN8is2QGjqGZvQXKruWIp+38llSmuNctNbR8pucNKYpyszy+Mh1DUxQjh9OPEPZTo9mRLMiJ4x0ai+Vvs2jEij5On3XTKLyIpyfKjXvsRmqcBJ4bFU5877rJpjjBbyKwiMr4IK8lPMu2MZpx/8TF/vkNF3ryFaMOfu2xFG38DxVe8k03g4jz1yemMLHzIS5g8Bd6BvGW9795orn0oRWC8NuxBGHGcgXHLxc89/TMUFVkGqGdSIMbv8gKQalSQiAJ1hedZMITuDt3whIi4Zg==",
    "ftp": "stream1",
    "name": "Garden PTZ",
    "onvifHost": "192.168.1.30:8080",
    "ptzControls": true,
    "retriggerWindow": 30,
    "rtspTransport": "tcp",
    "snapshotUri": "http://192.168.1.30/tmpfs/auto.jpg",
    "streams": {},
    "useRtspAuth": false
  },
  "stream": {
    "audio": true,
    "audio_bitrate": "16000",
    "audio_encoding": "G711",
    "audio_sample_rate": 8000,
    "defaultOnMultiDisplay": false,
    "descr": "HD",
    "media_server_input_uri": "http://localhost:8085/live/stream?suuid=stream1",
    "motion": {
      "enabled": false,
      "mask_file": "",
      "threshold": 1500,
      "trigger_recording_on": ""
    },
    "netcam_uri": "rtsp://192.168.1.30:554/11",
    "preambleFrames": 375,
    "recording": {
      "enabled": true,
      "location": "rec1",
      "recording_src_url": "http://localhost:8085/h/stream?suuid=stream1",
      "uri": "http://localhost:8084/recording/rec1/"
    },
    "uri": "ws://localhost:8085/ws/stream?suuid=stream1",
    "video_height": 1440,
    "video_width": 2560,
    "selected": false
  }
}

###
POST http://localhost:8080/motion/downloadRecording
Content-Type: application/json

{
  "stream": {
    "audio": true,
    "audio_bitrate": "16000",
    "audio_encoding": "G711",
    "audio_sample_rate": 8000,
    "defaultOnMultiDisplay": false,
    "descr": "HD",
    "media_server_input_uri": "http://localhost:8085/live/stream?suuid=stream1",
    "motion": {
      "enabled": false,
      "mask_file": "",
      "threshold": 1500,
      "trigger_recording_on": ""
    },
    "netcam_uri": "rtsp://192.168.1.30:554/11",
    "preambleFrames": 375,
    "recording": {
      "enabled": true,
      "location": "rec1",
      "recording_src_url": "http://localhost:8085/h/stream?suuid=stream1",
      "uri": "http://localhost:8084/recording/rec1/"
    },
    "uri": "ws://localhost:8085/ws/stream?suuid=stream1",
    "video_height": 1440,
    "video_width": 2560,
    "selected": false
  },
  "manifest": "rec1-1708346095_.m3u8"
}

###

POST http://localhost:8080/motion/deleteRecording
Content-Type: application/json
Accept: application/json

{
"stream": {
"audio": true,
"audio_bitrate": "16000",
"audio_encoding": "G711",
"audio_sample_rate": 8000,
"defaultOnMultiDisplay": false,
"descr": "HD",
"media_server_input_uri": "http://localhost:8085/live/stream?suuid=stream1",
"motion": {
"enabled": false,
"mask_file": "",
"threshold": 1500,
"trigger_recording_on": ""
},
"netcam_uri": "rtsp://192.168.1.30:554/11",
"preambleFrames": 375,
"recording": {
"enabled": true,
"location": "rec1",
"recording_src_url": "http://localhost:8085/h/stream?suuid=stream1",
"uri": "http://localhost:8084/recording/rec1/"
},
"uri": "ws://localhost:8085/ws/stream?suuid=stream1",
"video_height": 1440,
"video_width": 2560,
"selected": false
},
"fileName": ""
}

###
POST http://localhost:8080/ptz/preset
Content-Type: application/json

{
  "onvifBaseAddress": "192.168.1.30:8080",
  "creds": "JFM3r9UZRmLGPN4ts+xjQSco3tjM07DD5ITS0kviMzVttgqUBLc0b+kpLn88+mTPj6esN8is2QGjqGZvQXKruWIp+38llSmuNctNbR8pucNKYpyszy+Mh1DUxQjh9OPEPZTo9mRLMiJ4x0ai+Vvs2jEij5On3XTKLyIpyfKjXvsRmqcBJ4bFU5877rJpjjBbyKwiMr4IK8lPMu2MZpx/8TF/vkNF3ryFaMOfu2xFG38DxVe8k03g4jz1yemMLHzIS5g8Bd6BvGW9795orn0oRWC8NuxBGHGcgXHLxc89/TMUFVkGqGdSIMbv8gKQalSQiAJ1hedZMITuDt3whIi4Zg==",
  "operation": 2,
  "preset": "Preset032"
}

###

POST http://localhost:8080/ptz/move
Content-Type: application/json

{
  "onvifBaseAddress": "192.168.1.308:8080",
  "creds": "JFM3r9UZRmLGPN4ts+xjQSco3tjM07DD5ITS0kviMzVttgqUBLc0b+kpLn88+mTPj6esN8is2QGjqGZvQXKruWIp+38llSmuNctNbR8pucNKYpyszy+Mh1DUxQjh9OPEPZTo9mRLMiJ4x0ai+Vvs2jEij5On3XTKLyIpyfKjXvsRmqcBJ4bFU5877rJpjjBbyKwiMr4IK8lPMu2MZpx/8TF/vkNF3ryFaMOfu2xFG38DxVe8k03g4jz1yemMLHzIS5g8Bd6BvGW9795orn0oRWC8NuxBGHGcgXHLxc89/TMUFVkGqGdSIMbv8gKQalSQiAJ1hedZMITuDt3whIi4Zg==",
  "moveDirection": 3
}

###

POST http://localhost:8080/ptz/stop
Content-Type: application/json

{
  "onvifBaseAddress": "192.168.1.30:8080",
  "creds": "JFM3r9UZRmLGPN4ts+xjQSco3tjM07DD5ITS0kviMzVttgqUBLc0b+kpLn88+mTPj6esN8is2QGjqGZvQXKruWIp+38llSmuNctNbR8pucNKYpyszy+Mh1DUxQjh9OPEPZTo9mRLMiJ4x0ai+Vvs2jEij5On3XTKLyIpyfKjXvsRmqcBJ4bFU5877rJpjjBbyKwiMr4IK8lPMu2MZpx/8TF/vkNF3ryFaMOfu2xFG38DxVe8k03g4jz1yemMLHzIS5g8Bd6BvGW9795orn0oRWC8NuxBGHGcgXHLxc89/TMUFVkGqGdSIMbv8gKQalSQiAJ1hedZMITuDt3whIi4Zg=="
}

###
POST http://localhost:8080/ptz/ptzPresetsInfo
Content-Type: application/json

{
  "onvifBaseAddress": "192.168.1.30:8080",
  "creds": "JFM3r9UZRmLGPN4ts+xjQSco3tjM07DD5ITS0kviMzVttgqUBLc0b+kpLn88+mTPj6esN8is2QGjqGZvQXKruWIp+38llSmuNctNbR8pucNKYpyszy+Mh1DUxQjh9OPEPZTo9mRLMiJ4x0ai+Vvs2jEij5On3XTKLyIpyfKjXvsRmqcBJ4bFU5877rJpjjBbyKwiMr4IK8lPMu2MZpx/8TF/vkNF3ryFaMOfu2xFG38DxVe8k03g4jz1yemMLHzIS5g8Bd6BvGW9795orn0oRWC8NuxBGHGcgXHLxc89/TMUFVkGqGdSIMbv8gKQalSQiAJ1hedZMITuDt3whIi4Zg=="
}

###

POST http://localhost:8080/onvif/getSnapshot HTTP/1.1
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Authorization: my-auth-token
Connection: keep-alive
Content-Length: 398
Content-Type: application/json
Host: localhost:4200
Origin: http://localhost:4200
Referer: http://localhost:4200/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
sec-ch-ua: "Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"

{
  "url": "http://192.168.1.43/cgi-bin/api.cgi?cmd=onvifSnapPic&channel=0",
  "cred": "jIgm9mSRneOwtulK1E2cU50+NmP0BIg/jxHGN/OtPhC6+rR6yue5SIR7LCigRWP35rr8bHLhN5hXPlkKMh2v0m0M3HoFvDObK/Q6JfTHHyrMxinvTOkUmiif02odX/KJup/Xf1Z/I2dYaAIEOlaoj0t/t+GfKnbqE+bFc3Pj5fiBP0ToP/2SPSjoVhAsc6CySeLLZdRsaFtsmX86CIpP5LjjLmPDhIjhgrtzdu6E/hCuhAnBu1G3QJy671XQz+v5/A1W8566ye/hK3Hzi15TLvigwTMc3mZTT5DaDaopF3E4eqNfe19/PvjfzJwCYjgga8OTAncQSA+8UF+Zinms2Q=="
}

###

{
  "url": "http://192.168.1.30/tmpfs/auto.jpg",
  "cred": "JFM3r9UZRmLGPN4ts+xjQSco3tjM07DD5ITS0kviMzVttgqUBLc0b+kpLn88+mTPj6esN8is2QGjqGZvQXKruWIp+38llSmuNctNbR8pucNKYpyszy+Mh1DUxQjh9OPEPZTo9mRLMiJ4x0ai+Vvs2jEij5On3XTKLyIpyfKjXvsRmqcBJ4bFU5877rJpjjBbyKwiMr4IK8lPMu2MZpx/8TF/vkNF3ryFaMOfu2xFG38DxVe8k03g4jz1yemMLHzIS5g8Bd6BvGW9795orn0oRWC8NuxBGHGcgXHLxc89/TMUFVkGqGdSIMbv8gKQalSQiAJ1hedZMITuDt3whIi4Zg=="
}
