
package org.oasis_open.docs.wsn.bw_2;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * Generated source version: 3.3.2
 */

@WebFault(name = "NoCurrentMessageOnTopicFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class NoCurrentMessageOnTopicFault extends Exception {

    private org.oasis_open.docs.wsn.b_2.NoCurrentMessageOnTopicFaultType noCurrentMessageOnTopicFault;

    public NoCurrentMessageOnTopicFault() {
        super();
    }

    public NoCurrentMessageOnTopicFault(String message) {
        super(message);
    }

    public NoCurrentMessageOnTopicFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public NoCurrentMessageOnTopicFault(String message, org.oasis_open.docs.wsn.b_2.NoCurrentMessageOnTopicFaultType noCurrentMessageOnTopicFault) {
        super(message);
        this.noCurrentMessageOnTopicFault = noCurrentMessageOnTopicFault;
    }

    public NoCurrentMessageOnTopicFault(String message, org.oasis_open.docs.wsn.b_2.NoCurrentMessageOnTopicFaultType noCurrentMessageOnTopicFault, java.lang.Throwable cause) {
        super(message, cause);
        this.noCurrentMessageOnTopicFault = noCurrentMessageOnTopicFault;
    }

    public org.oasis_open.docs.wsn.b_2.NoCurrentMessageOnTopicFaultType getFaultInfo() {
        return this.noCurrentMessageOnTopicFault;
    }
}
