package org.oasis_open.docs.wsn.bw_2;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.5
 * Generated source version: 4.0.5
 *
 */
@WebService(targetNamespace = "http://docs.oasis-open.org/wsn/bw-2", name = "PullPoint")
@XmlSeeAlso({org.oasis_open.docs.wsrf.r_2.ObjectFactory.class, org.oasis_open.docs.wsrf.bf_2.ObjectFactory.class, org.oasis_open.docs.wsn.b_2.ObjectFactory.class, org.oasis_open.docs.wsn.t_1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PullPoint {

    @WebMethod(operationName = "Notify")
    @Oneway
    public void notify(

        @WebParam(partName = "Notify", name = "Notify", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.Notify notify
    );

    @WebMethod(operationName = "DestroyPullPoint")
    @WebResult(name = "DestroyPullPointResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "DestroyPullPointResponse")
    public org.oasis_open.docs.wsn.b_2.DestroyPullPointResponse destroyPullPoint(

        @WebParam(partName = "DestroyPullPointRequest", name = "DestroyPullPoint", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.DestroyPullPoint destroyPullPointRequest
    ) throws UnableToDestroyPullPointFault, org.oasis_open.docs.wsrf.rw_2.ResourceUnknownFault;

    @WebMethod(operationName = "GetMessages")
    @WebResult(name = "GetMessagesResponse", targetNamespace = "http://docs.oasis-open.org/wsn/b-2", partName = "GetMessagesResponse")
    public org.oasis_open.docs.wsn.b_2.GetMessagesResponse getMessages(

        @WebParam(partName = "GetMessagesRequest", name = "GetMessages", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
        org.oasis_open.docs.wsn.b_2.GetMessages getMessagesRequest
    ) throws UnableToGetMessagesFault, org.oasis_open.docs.wsrf.rw_2.ResourceUnknownFault;
}
