
package org.oasis_open.docs.wsn.bw_2;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * Generated source version: 4.0.5
 */

@WebFault(name = "UnableToGetMessagesFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnableToGetMessagesFault extends Exception {

    private org.oasis_open.docs.wsn.b_2.UnableToGetMessagesFaultType faultInfo;

    public UnableToGetMessagesFault() {
        super();
    }

    public UnableToGetMessagesFault(String message) {
        super(message);
    }

    public UnableToGetMessagesFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UnableToGetMessagesFault(String message, org.oasis_open.docs.wsn.b_2.UnableToGetMessagesFaultType unableToGetMessagesFault) {
        super(message);
        this.faultInfo = unableToGetMessagesFault;
    }

    public UnableToGetMessagesFault(String message, org.oasis_open.docs.wsn.b_2.UnableToGetMessagesFaultType unableToGetMessagesFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = unableToGetMessagesFault;
    }

    public org.oasis_open.docs.wsn.b_2.UnableToGetMessagesFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
