
package org.oasis_open.docs.wsn.bw_2;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.0.5
 * Generated source version: 4.0.5
 */

@WebFault(name = "UnsupportedPolicyRequestFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnsupportedPolicyRequestFault extends Exception {

    private org.oasis_open.docs.wsn.b_2.UnsupportedPolicyRequestFaultType faultInfo;

    public UnsupportedPolicyRequestFault() {
        super();
    }

    public UnsupportedPolicyRequestFault(String message) {
        super(message);
    }

    public UnsupportedPolicyRequestFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UnsupportedPolicyRequestFault(String message, org.oasis_open.docs.wsn.b_2.UnsupportedPolicyRequestFaultType unsupportedPolicyRequestFault) {
        super(message);
        this.faultInfo = unsupportedPolicyRequestFault;
    }

    public UnsupportedPolicyRequestFault(String message, org.oasis_open.docs.wsn.b_2.UnsupportedPolicyRequestFaultType unsupportedPolicyRequestFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = unsupportedPolicyRequestFault;
    }

    public org.oasis_open.docs.wsn.b_2.UnsupportedPolicyRequestFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
